name: "stable_diffusion_2_1"
backend: "python"
max_batch_size: 16
input [
  {
    name: "INPUT_0"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]
output [
  {
    name: "OUTPUT_0"
    data_type: TYPE_INT8
    dims: [ 768, 768, 3 ]
  }
]